---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-node-exporter
  vars:
    node_exporter_system_group: "root"
    node_exporter_system_user: "root"
    node_exporter_textfile_dir: ""
    node_exporter_enabled_collectors:
      - systemd
